stages:
- name: Build
  steps:
  - runScriptConfig:
      image: maven:3.3-jdk-8
      shellScript: mvn clean install package
- name: Push
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: images/dubbo-back:v1
      pushRemote: true
      registry: 10.0.0.88:7709
    env:
      CICD_LOCAL_REGISTRY: 10.0.0.88:7708
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
