apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-dp-v1
spec:
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: back
  replicas: 2
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
      - name: back
        image: images/dubbo-back:v1
        imagePullPolicy: IfNotPresent
